### ISSUE TITLE
Planning Document: version 0.1

### ISSUE THREAD

**Issue by jon-nfc** [nofusscomputing/centurion_erp_ui#17]
version 0.1 is the initial release of the UI.

## Details

for v0.1 to be released it must have feature parity with the current Centurion UI. No additional features are required or should be added.

This release is to serve as the starting point to develop the UI to be production ready.

## Links

- Blocked by: nofusscomputing/centurion_erp#344
- Blocked by: nofusscomputing/centurion_erp#345

- Related: #1 

## Requirements

- [ ] Feature parity with the current Centurion UI

## Tasks

- [ ] Custom params hook for url standard

    _Required so that the url can be correctly built for navigation and the fetching of data_

- [ ] Form validation errors to be displayed alongside field
