### ISSUE TITLE
Planning Document: version 0.2.0

### ISSUE THREAD

**Issue by jon-nfc** [nofusscomputing/centurion_erp_ui#23]
v0.2.0 release

## Details

This release is to correct, implement and fix anything that has been picked up from a manual review of the ui.

## Tasks

- Common

    - [x] #26

    - [x] items own name is a http link when it should not be within details page
    - [x] Time to be formatted to browser localtime

    - [x] #25

- Ticket Common

    - ~~[ ] No add button for related tickets~~ _moved #29_
    - ~~[ ] No add button for linked devices~~ _moved #29_
    - [x] reply with task button needs to be removed _feature no longer required_
    - [x] reply with notification button needs to be removed _feature no longer required_

- Centurion API

    - [ ] nofusscomputing/centurion_erp#387
    - [ ] nofusscomputing/centurion_erp#388

- Access

    - [x] Cant edit team _no link to it from interface_

- Assistance

    - [x] Clicking on add request causes crash _params are incorrect: {"action":"add","module":"assistance","model":"request","pk":"add","common_model":"ticket","common_pk":null}_
    - Requests
        - [x] Ticket description field in edit is not a text area
        - ~~[ ] Add time to action comments~~ _moved #29_
        - [x] Cant edit ticket comment
        - ~~[ ] Cant reply to comment~~ _moved #29_
    - KB articles
        - [x] Article content field is not rendered markdown
        - ~~[ ] Cant add note to kb articles _HTTP/405 returned_~~ _moved, see nofusscomputing/centurion_erp/issues/389_

- ITAM

    - Devices
        - [x] When attempting to create a device HTTP/500 is returned
        - [x] devices own name is a http link when it should not be
        - [x] editing a device returns HTTP/500
        - [x] when adding software to a device, the device field is visible
        - [x] Editing device software returns HTTP/404. _weblog shows url as `/api/v2/itam/device/24/undefined/6917`_
        - [x] adding a ticket to a device from device details presents the wrong interface. _should be a list of tickets_
            - url for button appears to be wrong _`/core/device/24/item_ticket/add`_
        - [x] #25
        - [x] editing field `configuration` throws an exception on centurion

            ``` log

            File "/home/sysadmin/git/centurion-erp/app/itam/models/device.py", line 123, in validate_config_keys_not_reserved
                if invalid_key in value.keys():
                                ^^^^^^^^^^
            AttributeError: 'str' object has no attribute 'keys'

            ```

    - Operating System
        - [x] When attempting to create a device HTTP/500 is returned
        - [x] clicking on an os version gives an error _no entries in api web logs_
        - [x] OR installations table empty _js log and web log shows attempt to access URL `/api/v2/undefined`_
        - [x] #25
        - ~~[ ] No navigation icon for operating system~~ _moved #29_

    - Software
        - [x] cant add new software. _server reports HTTP/500_
        - [x] clicking on software version returns error. _no entry in web log_
        - [x] installations tab is empty. _web log shows attempt to access `/api/v2/undefined`_
        - [x] ticket tab `add` shows wrong interface, should be list of tickets
        - ~~[ ] ticket tab `add` interface cancel button returns to wrong url~~ _moved to nofusscomputing/centurion_erp#388_
        - [x] #25

- ITIM

    - Changes
        - [x] add change gives error `params are incorrect: {"action":"add","module":"itim","model":"change","pk":"add","common_model":"ticket","common_pk":null}`

    - Cluster
        - [x] Cant add new cluster server rtns HTTP/500
        - [x] #24
        - ~~[ ] attempting to add a note to a cluster returns HTTP/500~~ _moved, see nofusscomputing/centurion_erp/issues/389_
        - [x] #25

    - Service
        - [x] Can't add service http/400 returned _possibly due to no org specified and fields not showing errors_
        - [x] Service edit shows config as `[object Object]`
        - [x] adding ticket to service wrong interface, should be list of tickets
        - ~~[ ] adding ticket to service cancel button has wrong link~~ _moved to nofusscomputing/centurion_erp#388_
        - [x] #25

- Config Management

    - Group
        - [x] Can't add group http/500 returned
        - [x] Child groups should not be visible on group index page
        - [x] edit group page shows config as `[object Object]`
        - [x] clicking on hosts tab shows nothing. _web log shows url access to `/api/v2/undefined`_
        - [x] adding ticket to group wrong interface, should be list of tickets
        - ~~[ ] adding ticket to group cancel button has wrong link~~ _moved to nofusscomputing/centurion_erp#388_
        - [x] #25

- Project Management

    - Project
        - [x] Can't add group http/500 returned
        - [x] clicking add task on tasks tab shows error _`params are incorrect: {"action":"add","module":"project_management","model":"project_task","pk":"add","common_model":"project","common_pk":"2"}`_
        - [x] milestone add interface not using datetime field
        - [x] attempting to view an existing milestone presents the error page
        - ~~[ ] attempting to add a note fails. `http/500 shown on web log`~~ _moved, see nofusscomputing/centurion_erp/issues/389_
        - ~~[ ] notes show notes for other items.~~ _moved, see nofusscomputing/centurion_erp/issues/389_
        - [x] adding ticket to group wrong interface, should be list of tickets
        - ~~[ ] adding ticket to group cancel button has wrong link~~ _moved to nofusscomputing/centurion_erp#388_
        - [x] #25

- Settings

    - Task Log
        - [x] Cant view a task log entry, no link available

    - System
        - [x] application settings fails with http/404

## New Problems Found

**These will be fixed in the next release.**

- Assistance

    - Request

        - ~~[ ] Ticket Add layout cancel button wrong link~~ _moved to nofusscomputing/centurion_erp#388_

- ITAM

    - Devices

        - [ ] When editing device software the fields are not populated with data unless you refresh the page

    - Operating System

        - [ ] When editing OS Version the fields are not populated with data unless you refresh the page

    - Software

        - [ ] When editing Software Version the fields are not populated with data unless you refresh the page

- ITIM

    - change

        - [ ] Ticket Add layout cancel button wrong link

    - incident

        - [ ] Ticket Add layout cancel button wrong link

    - problem

        - [ ] Ticket Add layout cancel button wrong link

- Project Management

    - Project

        - [ ] When adding a ticket and submit is clicked an exception is thrown

- Centurion API

    - [ ] **Operating System** no installation in `._urls` for table lookup

    - [ ] **Software** no installation in `._urls` for table lookup

    - [ ] **cluster** no nodes in `._urls` for table lookup

    - [ ] **cluster** no devices in `._urls` for table lookup

    - [ ] **cluster** no services in `._urls` for table lookup

    - [ ] **Config Group** no hosts in `._urls` for table lookup

    - [ ] **Ticket Comment** when creating a ticket comment it fails with error `organization required`. this field must be set by the serializer to the tickets organization.

    - [ ] nofusscomputing/centurion_erp#389

    - [ ] On completion of nofusscomputing/centurion_erp#388, adjust **ALL** cancel buttons and return URL to use `metadata[return_url]`

## Links

- work for UI testing nofusscomputing/centurion_erp@8659ba3b7c2f7787bb9cff507da94275d93f4f8a
