### ISSUE TITLE
complete form fields implementation

### ISSUE THREAD

**Issue by jon-nfc** [nofusscomputing/centurion_erp_ui#26]
The form fields feature must be finished so that further development can occur

## Links

- Blocked By: nofusscomputing/centurion_erp#388

- Related: #23
- Related: nofusscomputing/centurion_erp#387

## Tasks

- [x] #4

    - [x] On field update of `DateTime` field, append the timezone to it so that it's stored accuratly.

        - [x] :mag: _Find out if Django will use this timezone or the user configured timezone when storing_

            _Uses the TZ in the field if specified. i.e. adding `z` to DTG correctly stores the value as UTC_

- [x] Form dropdowns that do a separate lookup to populate

- [x] Be able to specify the textbox details. _will allow model notes to be an actual text area_

    - [x] confirm that once populated that the existing value is populated when editing

- [x] when adding a date to datetime field, it's in local time and not converted back to the server TZ

- [x] set-up select for multi-select

- ~~[ ] Field errors to display within the form~~ Feature already existed and works when API returns HTTP/400 with field errors
- [x] Non-field errors to display at the top of the window
