### ISSUE TITLE
Planning Document: version 0.3.0

### ISSUE THREAD

**Issue by jon-nfc** [nofusscomputing/centurion_erp_ui#29]
v0.3.0 release

## Details
This release is to correct, implement and fix anything that has been picked up from a manual review of the ui.

## Requirements

- [x] Add user to a team
    _feature yet to be implemented_

- ~~[ ] `urlBuilder` to cater for three model path~~ _No longer relevant due to nofusscomputing/centurion_erp#410_
    _`/access/organization/1/team/1/user/add`_

- [x] User be able to edit own settings

## Tasks

- [x] Replicate Page footer from Centurion old UI
- [x] Incorrect url for navigate event on form post
    _confirm the navigate url is using the URL from metadata_

- Ticket Common

    - [ ] No add button for related tickets
    - [ ] No add button for linked devices

- Centurion API

    - [x] nofusscomputing/centurion_erp#366
    - [x] nofusscomputing/centurion_erp#387
    - [x] nofusscomputing/centurion_erp#388

- Assistance

    - Requests
        - [x] Add time to action comments
        - [x] Cant reply to comment

- ITAM

    - Devices

        - [x] When editing device software the fields are not populated with data unless you refresh the page

    - Operating System

        - [x] When editing OS Version the fields are not populated with data unless you refresh the page
        - [x] No navigation icon for operating system

    - Software

        - [x] When editing Software Version the fields are not populated with data unless you refresh the page

- ITIM

    - change

        - [x] Ticket Add layout cancel button wrong link

    - incident

        - [x] Ticket Add layout cancel button wrong link

    - problem

        - [x] Ticket Add layout cancel button wrong link

- Project Management

    - Project

        - [x] When adding a ticket and submit is clicked an exception is thrown

- Centurion API

    - [x] **Operating System** no installation in `._urls` for table lookup

    - [x] **Software** no installation in `._urls` for table lookup

    - [x] **cluster** no nodes in `._urls` for table lookup

    - [x] **cluster** no devices in `._urls` for table lookup

    - [x] **cluster** no services in `._urls` for table lookup

    - [x] **Config Group** no hosts in `._urls` for table lookup

    - [x] **Ticket Comment** when creating a ticket comment it fails with error `organization required`. this field must be set by the serializer to the tickets organization.

    - [ ] nofusscomputing/centurion_erp#389

    - [x] On completion of nofusscomputing/centurion_erp#388, adjust **ALL** cancel buttons and return URL to use `metadata[return_url]`
